version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run: python setup.py install && pip install -r requirements_dev.txt
  test:
    requires:
      - build
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run: python setup.py test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
